<?php

########################################################################
# Extension Manager/Repository config file for ext: "icticontent"
#
# Auto generated by Extension Builder 2012-03-22
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'ICTI structured content framework',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Jose Antonio Guerra',
	'author_email' => 'jaguerra@icti.es',
	'author_company' => 'ICTI Internet Passion S.L.',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '3.0.0',
	'constraints' => array(
    'depends' => array(
      'cms' => '6.2.0-6.2.99',
      'ictiextbase' => '2.0.0-2.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
