<?php

########################################################################
# Extension Manager/Repository config file for ext: "icticontent"
#
# Auto generated by Extension Builder 2012-02-24
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'ICTI structured content framework',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Jose Antonio Guerra',
	'author_email' => 'jaguerra@icti.es',
	'author_company' => 'ICTI Internet Passion S.L.',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0-0.0.0,',
			'fluid' => '1.3.0-0.0.0,',
			'fed' => '1.4.10-0.0.0,',
			'ictiextbase' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>