<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-07-31 12:25

$extensionPath = t3lib_extMgm::extPath('icticontent');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_icticontent_controller_basecontroller' => $extensionClassesPath . 'Controller/BaseController.php',
	'tx_icticontent_controller_categorycontrollertest' => $extensionPath . 'Tests/Unit/Controller/CategoryControllerTest.php',
	'tx_icticontent_controller_contentcontroller' => $extensionClassesPath . 'Controller/ContentController.php',
	'tx_icticontent_controller_contentcontrollertest' => $extensionPath . 'Tests/Unit/Controller/ContentControllerTest.php',
	'tx_icticontent_controller_countrycontrollertest' => $extensionPath . 'Tests/Unit/Controller/CountryControllerTest.php',
	'tx_icticontent_controller_geoareacontrollertest' => $extensionPath . 'Tests/Unit/Controller/GeoAreaControllerTest.php',
	'tx_icticontent_controller_provincecontrollertest' => $extensionPath . 'Tests/Unit/Controller/ProvinceControllerTest.php',
	'tx_icticontent_domain_model_author' => $extensionClassesPath . 'Domain/Model/Author.php',
	'tx_icticontent_domain_model_authortest' => $extensionPath . 'Tests/Unit/Domain/Model/AuthorTest.php',
	'tx_icticontent_domain_model_category' => $extensionClassesPath . 'Domain/Model/Category.php',
	'tx_icticontent_domain_model_categorytest' => $extensionPath . 'Tests/Unit/Domain/Model/CategoryTest.php',
	'tx_icticontent_domain_model_content' => $extensionClassesPath . 'Domain/Model/Content.php',
	'tx_icticontent_domain_model_contenttest' => $extensionPath . 'Tests/Unit/Domain/Model/ContentTest.php',
	'tx_icticontent_domain_model_country' => $extensionClassesPath . 'Domain/Model/Country.php',
	'tx_icticontent_domain_model_countrytest' => $extensionPath . 'Tests/Unit/Domain/Model/CountryTest.php',
	'tx_icticontent_domain_model_geoarea' => $extensionClassesPath . 'Domain/Model/GeoArea.php',
	'tx_icticontent_domain_model_geoareatest' => $extensionPath . 'Tests/Unit/Domain/Model/GeoAreaTest.php',
	'tx_icticontent_domain_model_geolocation' => $extensionClassesPath . 'Domain/Model/GeoLocation.php',
	'tx_icticontent_domain_model_geolocationtest' => $extensionPath . 'Tests/Unit/Domain/Model/GeoLocationTest.php',
	'tx_icticontent_domain_model_keyword' => $extensionClassesPath . 'Domain/Model/Keyword.php',
	'tx_icticontent_domain_model_keywordtest' => $extensionPath . 'Tests/Unit/Domain/Model/KeywordTest.php',
	'tx_icticontent_domain_model_media' => $extensionClassesPath . 'Domain/Model/Media.php',
	'tx_icticontent_domain_model_mediaexternal' => $extensionClassesPath . 'Domain/Model/MediaExternal.php',
	'tx_icticontent_domain_model_mediafile' => $extensionClassesPath . 'Domain/Model/MediaFile.php',
	'tx_icticontent_domain_model_mediatest' => $extensionPath . 'Tests/Unit/Domain/Model/MediaTest.php',
	'tx_icticontent_domain_model_province' => $extensionClassesPath . 'Domain/Model/Province.php',
	'tx_icticontent_domain_model_provincetest' => $extensionPath . 'Tests/Unit/Domain/Model/ProvinceTest.php',
	'tx_icticontent_domain_model_region' => $extensionClassesPath . 'Domain/Model/Region.php',
	'tx_icticontent_domain_model_regiontest' => $extensionPath . 'Tests/Unit/Domain/Model/RegionTest.php',
	'tx_icticontent_domain_model_typo3page' => $extensionClassesPath . 'Domain/Model/Typo3Page.php',
	'tx_icticontent_domain_model_typo3pagetest' => $extensionPath . 'Tests/Unit/Domain/Model/Typo3PageTest.php',
	'tx_icticontent_domain_repository_contentrepository' => $extensionClassesPath . 'Domain/Repository/ContentRepository.php',
	'tx_icticontent_domain_repository_countryrepository' => $extensionClassesPath . 'Domain/Repository/CountryRepository.php',
	'tx_icticontent_domain_repository_geoarearepository' => $extensionClassesPath . 'Domain/Repository/GeoAreaRepository.php',
	'tx_icticontent_service_filtersservice' => $extensionClassesPath . 'Service/FiltersService.php',
	'tx_icticontent_service_filtersservicetest' => $extensionPath . 'Tests/Unit/Service/FiltersServiceTest.php',
	'tx_icticontent_service_lookupservice' => $extensionClassesPath . 'Service/LookupService.php',
	'tx_icticontent_service_serviceinterface' => $extensionClassesPath . 'Service/ServiceInterface.php',
);
?>